### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by loicNorgeot** [loicNorgeot/numero#1]
# TODO

- [ ] Documenter l'installation et le développement
- [ ] Documenter l'utilisation
- [ ] Nettoyer le code et faire du Modèle-Vue-Controleur
- [ ] Ajouter une barre de chargement pour les objets depuis le menu
- [ ] Implémenter le système de groupes
- [ ] Implémenter une rotation fine en gimball
- [ ] Régler le picking qui dysfonctionne
- [ ] Valider visuellement le login
- [ ] Permettre de créer un nouvel assemblage
- [ ] Une fois une reconstruction sélectionnée, afficher les commentaires
- [ ] Afficher la date de chaque assemblage
- [ ] Mettre en place un système de commentaires
- [ ] Créer un plugin blender pour importer / exporter des reconstitutions
- [ ] Recharger fréquemment la liste des dernières versions
- [ ] Changer l'éclairage, les ombres, le background... etc.
- [ ] Rajouter à la selection un widget de manipulation (fleches sur les axes et rotation en z et en gimball)
- [ ] Régler le problème de l'outline qui disparait quand on sort du cadre
- [ ] Ajouter un mécanisme Undo/redo
- [ ] Régler le problème du smooth moche mais léger en réseau vs flat/plus lourd
- [ ] Ajouter la possibilité d'annuler le mouvement en cours avec le clic droit
- [ ] Vue orthographique / perspective
- [ ] Ne marche pas sur safari
- [ ] Option pour tout charger/supprimer/sélectionner
- [ ] Virer le fichier list.csv du dépot des objets, utiliser un appel à l'api "contents" à la place
- [ ] Safari sur Mac ne marche pas, ni apparement Firefox sur l'ordinateur de titien

# DONE
- [x] Ajouter des licenses
- [x] Permettre de supprimer un objet d'une reconstruction importée
- [x] Permettre la rotation pour plusieurs objets
- [x] Permettre de supprimer un objet de "loaded"
- [x] Permettre l'accès à un catalogue de reconstructions si non loggué
- [x] Au login, ne pas faire que des "append" dans la dropdown des dépots...
- [x] Faire fonctionner la rotation des objets
- [x] Afficher un lien vers le github et le dépot en cours d'édition dans la rubrique "scène"
- [x] Réfléchir au schéma administrateur / collaborateur / reader (par défaut) pour l'organisation
- [x] Mettre le login et la config dans un nouvel onglet
- [x] Faire x onglets: "File" avec la configuration et le login, "Import/Export" avec les options de sauvegarde, "Models" avec les widgets de manipulation et la liste des objets, et "About" avec des infos et liens (sketchfab par exemple).
- [x] Permettre la rotation sur Mac avec la touche commande
- [x] Implémenter le mouvement en Z
- [x] Créer une organisation, et y ajouter les utilisateurs intéressés pour manipuler
- [x] Ouvrir les ports d'un serveur pour accès extérieur
- [x] Réduire les échanges de buffer depuis l'API
- [x] Mettre l'écran de chargement de l'ISCD
- [x] Permettre de choisir l'adresse IP de l'API
- [x] Retenir le login d'une session à l'autre
- [x] Garder en mémoire les objets déjà chargés lors de l'étape de chargement
- [x] Documenter le déploiement
